#application: tpassing
#version: 1
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

beta_settings:
  cloud_sql_instances: tpassing-175603:us-central1:transpassing

default_expiration: "10m"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?[Tt]humbs\.db$
- ^(.*/)?.*\.psd$
